spring.application.name=ProductionManagement

# DataSource
# Postgresのドライバーの設定
spring.datasource.driver-class-name=org.postgresql.Driver
# データベースへの接続URLを設定
spring.datasource.url=jdbc:postgresql://localhost:5432/productionmanagement
#spring.datasource.url=jdbc:postgresql://db:5432/productionmanagement
# データベース接続のためのユーザー名を設定
spring.datasource.username=postgres
# データベース接続のためのパスワードを設定
spring.datasource.password=postgres
# SQLスクリプトの初期化モードを設定
spring.sql.init.mode=always
# Log表示設定
logging.level.com.example.webapp.repository=DEBUG

mybatis.mapper-locations=classpath:mapper/*.xml

mybatis.configuration.map-underscore-to-camel-case=true

# MyBatisのログレベルをDEBUGに設定
logging.level.com.production.management.mapper=DEBUG

# 実行されるSQLのバインドパラメータ（? の中身）も表示する場合
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG